### ISSUE TITLE
[Feature Request]只更新需要更新的 sticker image

### ISSUE THREAD

**Issue by whtsky** [CatDurian/durian-sticker#2]
https://durian.tiantian.codes/hashes.json

**Comment by helloqiu** [comment]
![image](https://user-images.githubusercontent.com/8971659/34106531-8a05b8c0-e433-11e7-91ff-c67f953d500c.png)

**Comment by whtsky** [comment]
![https://durian.tiantian.codes/%E4%B8%8D%E5%A6%82%E8%B7%B3%E8%88%9E-fs8.png](https://durian.tiantian.codes/%E4%B8%8D%E5%A6%82%E8%B7%B3%E8%88%9E-fs8.png)

**Comment by helloqiu** [comment]
根据 hash 的话，我试了试为什么我在本地 build 出来的图片和你 generate 出来的不一样，感觉是pngquant 在不同平台上实现不同。 @whtsky

**Comment by helloqiu** [comment]
感觉没法用 hash 从 sticker set 里面找到原来的 sticker，sticker download 下来是 webp 格式的，顶多找到需要更新的图片然后用 emoji 从 sticker set 里面把 sticker 更新掉。
真难（

**Comment by whtsky** [comment]
但是在 CI 下 generate 的结果应该是一样的呀。

> 找到需要更新的图片然后用 emoji 从 sticker set 里面把 sticker 更新掉。

感觉已经足够好了

**Comment by helloqiu** [comment]
![image](https://user-images.githubusercontent.com/8971659/34146746-24007d96-e4d6-11e7-96c6-c0cabae5c5e2.png)

**Comment by helloqiu** [comment]
Sad :(
Durian will live in our hearts forever.
